# -- Markup --
# These settings are required for the theme to function.

[goldmark] #Goldmark is a Markdown processor used by Hugo
[goldmark.renderer]
  unsafe = true #This allows Goldmark to render potentially unsafe content, such as raw HTML tags, which can be necessary for some themes or custom HTML elements.

[highlight]
  noClasses = false #When set to false, this tells Hugo to use classes for syntax highlighting. This can be useful for theming the code blocks with CSS.

[tableOfContents]
  startLevel = 2 #Defines the starting level for headings to include in the table of contents. In this case, it starts from the second level heading (<h2>).
  endLevel = 4  #Defines the ending level for headings to include in the table of contents, up to the fourth level heading (<h4>).
