# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]] # Defines a new menu item. Each [[main]] block represents a link in the main menu.
name = "Research"    #The display name of the menu link.
pageRef = "research" #References a specific page or section within the site.
weight = 10          # Determines the order of the menu item. Lower weight means higher up in the menu.

[[main]]
name = "About Me"
pageRef = "aboutme"
weight = 15

 [[main]]
   name = "Blog"
   pageRef = "blog"
   weight = 20

# [[main]]
#   name = "Samples"
#   parent = "Examples" #Indicates that the menu item is a sub-item of another menu item.
#   pageRef = "samples"
#   weight = 16

# [[main]]
#   name = "Showcase"
#   parent = "Examples"
#   pageRef = "examples"
#   weight = 30

# [[main]]
#   name = "Recipes"
#   parent = "Examples"
#   pageRef = "guides"
#   weight = 40

# [[main]]
#   name = "Users"
#   pageRef = "users"
#   weight = 90

# [[main]]
#   name = "Merch"
#   url = "https://www.teepublic.com/user/blowfish-store/t-shirts" #Specifies an external link.
#   weight = 100

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

# [[main]]
#   identifier = "twitter" #identifier and pre: Used for adding icons or identifiers, particularly useful for social media links.
#   pre = "x-twitter" 
#   url = "https://twitter.com/burufugu"
#   weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

# [[main]]
#   identifier = "github"
#   pre = "github"
#   url = "https://github.com/nunocoracao/blowfish"
#   weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

#[[footer]]
#  name = "Tags" #Links to the tags page with a weight of 10.
#  pageRef = "tags"
#  weight = 10

#[[footer]]
#  name = "Authors" #Links to the authors page with a weight of 20
#  pageRef = ""
#  weight = 20


# menu.toml: This file configures your site's navigation menus.
# It includes definitions for main and footer menus, specifying the items and their order.
