# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "princess"  #Sets the color scheme to "avocado".
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true  #Enables automatic switching between light and dark mode based on user preferences.

enableSearch = true  # Enables the search functionality.
enableCodeCopy = true  # Enables the ability to copy code snippets.

replyByEmail = false  # Disables replying by email.

mainSections = ["section1", "section2"]  #Lists the main sections of your site.
# robots = ""

disableImageOptimization = false # Keeps image optimization enabled.
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "/img/tree.jpg" # used as default for background images 
defaultFeaturedImage = "/img/tree.jpg" # used as default for featured images in all articles

highlightCurrentMenuArea = true
smartTOC = true #Enables a smart table of contents.
smartTOCHideUnfocusedChildren = false  # Keeps all TOC items visible.

giteaDefaultServer = "https://git.fsfe.org" #Sets default servers for Gitea and Forgejo.
forgejoDefaultServer = "https://v8.next.forgejo.org"

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer] # Configures the footer settings.
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]   #Configures the homepage layout and appearance.
  layout = "hero" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/img/tree.jpg" # used in: hero, and card
  showRecent = false
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = ""
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article] #Configures how articles are displayed.
  showDate = false
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  # showAuthorBottom = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  #showRelatedContent = true
  # relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = true
  showWordCount = false
  # sharingLinks = [ "linkedin", "twitter", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]
  showZenMode = true

[list] # Configures list views.
  showHero = true # Shows hero images.
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = false # only used when heroStyle equals background
  showBreadcrumbs = true
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = [] # No types of content are excluded from the sitemap.

[taxonomy]   # Configures how taxonomy terms are displayed.
  showTermCount = true   # Shows the number of items in each term.
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]   # Configures individual taxonomy term pages.
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[firebase]   # Placeholder for Fathom Analytics settings.
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # enableTrackEvent = true

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = true

#[buymeacoffee]   # Configuration for integrating Buy Me a Coffee.
#  identifier = "nunocoracao"
#  globalWidget = true   # Shows the widget globally.
#  globalWidgetMessage = ""
#  globalWidgetColor = "#FFDD00"
#  globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

# params.toml: This file is used to define custom parameters for your site. 
# These can include settings specific to your theme, such as color schemes, layout options, and other site customizations.